# Generated by Django 2.2.5 on 2019-12-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B_list',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('number', models.TextField(default='', null=True)),
                ('addressroad', models.TextField(default='', null=True)),
                ('addressgi', models.TextField(default='', null=True)),
                ('opentime', models.TextField(default='', null=True)),
                ('pageaddress', models.TextField(default='', null=True)),
                ('info', models.TextField(default='', null=True)),
                ('ellipsis_area', models.TextField(default='', null=True)),
                ('image', models.BinaryField(default='', null=True)),
            ],
        ),
    ]
